### ISSUE TITLE
Environment always defaults to production

### ISSUE THREAD

**Issue by jesalg** [bartoszkopinski/whenever-web#2]
First off, just wanted to say thanks for writing this gem. It's incredibly useful!

Although I'm running into this issue where the environment is always set to production even though RAILS_ENV on my server is set to staging:

```
$ env | grep RAILS
RAILS_ENV=staging
```

Any ideas what could be the issue? Do I need to set that somewhere else?

**Comment by bartoszkopinski** [comment]
@jesalg how do you tell it's set to production? does it happen only with the gem included?

**Comment by jesalg** [comment]
Sorry I meant the environment which this gem detects is always set to production regardless of what the RAILS_ENV is set to on the server:

![screenshot_1](https://cloud.githubusercontent.com/assets/885248/13014429/9fb5769a-d168-11e5-8a2a-85b0d143e95c.png)

As a result, when I try to trigger the jobs manually from the interface, it doesn't work because the sever doesn't have the credentials/config for that environment. 

So my question is, do I need to do something specific to set the correct environment other than having it in RAILS_ENV?

**Comment by bartoszkopinski** [comment]
@jesalg Try changing the command you use to run your server to something like: `RAILS_ENV=staging rails s` or `rails s -e staging`

**Comment by andre8888** [comment]
Yes I think this is an issue. I have RAILS_ENV=staging but settings is still showing production.

**Comment by jesalg** [comment]
@bartoszkopinski @andre8888 Yeah I basically had to abandon using this gem because of that environment issue. Couldn't figure out how/why it's getting populated incorrectly. Would love to find a solution to this.

**Comment by bartoszkopinski** [comment]
@andre8888 @jesalg what are your whenever settings?

This gem only prints them out, it doesn't set / modify env variables.

Looks like `production` is set as a default by whenever gem: 
https://github.com/javan/whenever/blob/9f3707615c654bd21211ca164ddc938eca3cba76/lib/whenever/setup.rb#L4

**Comment by jesalg** [comment]
@bartoszkopinski Interesting, I'll try explicitly setting the environment in my `schedule.rb` and see if that helps. Will let you know, thanks!

**Comment by jesalg** [comment]
@bartoszkopinski That did the trick. Just had to place this line at the top of my `schedule.rb`:

`set :environment, ENV['RAILS_ENV']`

Thanks for your help! Closing the issue :+1:
