### ISSUE TITLE
Missing layout admin

### ISSUE THREAD

**Issue by MaicolBen** [bartoszkopinski/whenever-web#6]
When I go to `/whenever` it throws `Missing template layouts/admin with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :coffee, :arb, :haml, :jbuilder]}`, if I add the empty view `layouts/admin`, it shows the jobs as expected but without styles, is the layout included in this proyect?

**Comment by duvaldt** [comment]
Any updates on this?

**Comment by bartoszkopinski** [comment]
@MaicolBen layout can be configured with:
```ruby
Whenever::Web.config.layout = '....'
```
The gem contains a very simple layout at `whenever/layouts/admin` if you want to use it but there are no styles. Best to integrate with your own layout (eg. if you're using active admin).

I'm not using `whenever` at the moment, but pull requests are welcome.

**Comment by MaicolBen** [comment]
> I'm not using `whenever` at the moment, but pull requests are welcome.

Me neither, feel free to close this issue.

**Comment by bartoszkopinski** [comment]
Sure, just replying for others because it has many  👍
